# Generated by Django 3.0.5 on 2020-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookieinformation',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
